# Copyright 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build packages

on:
  workflow_dispatch:
  schedule:
    # Runs at 11:00 AM UTC, which is 3:00 AM PST (UTC-8)
    - cron: '0 11 * * *'

jobs:
  build_packages:
    name: "${{ matrix.build-family }} :: Build ${{ matrix.package }} Package for ${{ matrix.python-version }}"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu packages.
          - runs-on: ubuntu-24.04
            build-family: linux-x86_64
            package: shortfin
            python-version: cp312-cp312
          - runs-on: ubuntu-24.04
            build-family: linux-x86_64
            package: shortfin
            python-version: cp313-cp313
          # TODO(#130): macOS
          # TODO(#130): Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        path: "c" # Windows can hit path length limits, so use a short path.
        submodules: false


    - name: Build shortfin (Linux x86_64, ${{ matrix.python-version }})
      if: "matrix.package == 'shortfin' && matrix.build-family == 'linux-x86_64'"
      shell: bash
      env:
        OUTPUT_DIR: "${{ github.workspace }}/bindist"
        OVERRIDE_PYTHON_VERSIONS: "${{ matrix.python-version }}"
      run: |
        [ -e ./bindist/* ] && rm ./bindist/*
        ./c/shortfin/build_tools/build_linux_package.sh

    - name: Upload python wheels
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: snapshot-${{ matrix.package }}-${{ matrix.build-family }}
        path: bindist

    - name: Release python wheels
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: bindist/*.whl
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "dev-wheels"
        name: "dev-wheels"
        body: "Automatic snapshot release of SHARK-Platform python wheels."
        removeArtifacts: false
        allowUpdates: true
        replacesArtifacts: true
        makeLatest: true
